name: Backport labeled merged pull requests
on:
  pull_request:
    types: [closed]
  issue_comment:
    types: [created]
jobs:
  build:
    name: Create backport PRs
    runs-on: ubuntu-latest
    permissions:
      contents: write # so it can comment
      pull-requests: write # so it can create pull requests
    # Only run when pull request is merged
    # or when a comment containing `/backport` is created
    if: >
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.merged
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '/backport')
      )
    steps:
      - uses: actions/checkout@v3
      - name: Create backport PRs
        uses: zeebe-io/backport-action@v0.0.7
        with:
          # Required
          # Token to authenticate requests to GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Required
          # Working directory for the backport action
          github_workspace: ${{ github.workspace }}

          # Optional
          # Regex pattern to match github labels
          # Must contain a capture group for target branchname
          # label_pattern: ^backport ([^ ]+)$
